### PR TITLE
Fix bug in vector_of_arrays.jl

### LINKED ISSUE #34: bug in sizehint!
sizehint! method uses `mul` which I guess should be `prod` ?

### PR DESCRIPTION
**Pull request by chrhck**
mul() should be prod()

Fixes #34

### CODE REVIEW

**Comment by oschulz** [comment]
Thanks! Should we add a test as well?

**Comment by chrhck** [comment]
Added a basic test for !sizehint - were you thinking of something more specific?

**Comment by oschulz** [comment]
>  Added a basic test for !sizehint - were you thinking of something more specific?

Looks good to me!

**Comment by oschulz** [comment]
Thanks again @chrhck !

https://github.com/JuliaRegistries/General/pull/94699

**Pull request merged**
